<a href="https://colab.research.google.com/github/Ranjith-arch/LetsupgradeDataScience/blob/main/Day3_datascience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
 import numpy as np

 # Question1

In [2]:
 
# Create a numpy array starting from 2 till 50 with a stepsize of 3.
# a=np.array([i for i in range(2,50,3)])
a=np.arange(2,50,3)
print(a)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question2

In [3]:
 
# Accept two lists of 5 elements each from the user.
# Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.
l1=[]
l2=[]
for _ in range(5):
    l1.append(int(input())) #input
for _ in range(5):
    l2.append(int(input())) #input
l1=np.array(l1)
l2=np.array(l2)
l=np.append(l1,l2)
l.sort()
print(l)

8390
990
0000
766
6
89
789
89
3
36
[   0    3    6   36   89   89  766  789  990 8390]


 # Question3

In [4]:
 
# Write a code snippet to find the dimensions of a ndarray and its size.
ndarr=np.array([[1,2,3],[3,4,5],[4,5,6]])
print(ndarr.shape)
print(ndarr.size)

(3, 3)
9


# Question4

In [5]:
 
# How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
b=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(b)
b=b.reshape(4,3)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


 # Question5

In [6]:
 
# Consider two square numpy arrays. Stack them vertically and horizontally.
# Hint: Use vstack(), hstack()
s1=np.arange(16).reshape(4,4)
s2=np.arange(16).reshape(4,4)
print("Stacking vertically")
print(np.hstack((s1,s2)))
print("------------------------")
print("Stacking horizontally")
print(np.vstack((s1,s2)))

Stacking vertically
[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]
 [12 13 14 15 12 13 14 15]]
------------------------
Stacking horizontally
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


 # Question6

In [7]:
 
# How to get unique items and counts of unique items?
number_list = np.array([1, 1, 2, 3, 4, 4, 1])
(unique, counts) = np.unique(number_list, return_counts=True)
frequencies = np.asarray((unique, counts)).T
print(frequencies)

[[1 3]
 [2 1]
 [3 1]
 [4 2]]
